name: "tradictional-generation-tasks"
type: "gen"
path: "llm/processed_data"
module: "evaluation.tasks.GenerationTask"
language: "en"
file-pattern:
  multi_nli: "**/multi_nli_processed.jsonl"
  imdb: "**/imdb_processed.jsonl"
  sciq: "**/sciq_processed.jsonl"
  cnn_dailymail3.0.0: "**/cnn_dailymail3.0.0_processed.jsonl"
  anli: "**/anli_processed.jsonl"
  ai2_arcARC-Easy: "**/ai2_arcARC-Easy_processed.jsonl"
  emo: "**/emo_processed.jsonl"
  quoref: "**/quoref_processed.jsonl"
  commonsense_qa: "**/commonsense_qa_processed.jsonl"
  hotpot_qafullwiki: "**/hotpot_qafullwiki_processed.jsonl"
  samsum: "**/samsum_processed.jsonl"
  racehigh: "**/racehigh_processed.jsonl"
  openbookqaadditional: "**/openbookqaadditional_processed.jsonl"
  raceall: "**/raceall_processed.jsonl"
  feverv1.0: "**/feverv1.0_processed.jsonl"
  math_qa: "**/math_qa_processed.jsonl"
  ai2_arcARC-Challenge: "**/ai2_arcARC-Challenge_processed.jsonl"
  racemiddle: "**/racemiddle_processed.jsonl"
  feverv2.0: "**/feverv2.0_processed.jsonl"
  openbookqamain: "**/openbookqamain_processed.jsonl"
workers: 20
shot: 1
